In [2]:
# Series 
# Pandas Series is a one-dimesional Labelled array capable of holding any data type

%pip install pandas

Requirement already satisfied: pandas in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import pandas as pd

hikes = pd.Series([10.5, 6.5, 7.5, 5.5],
                   index=['Mani', 'Rahul', 'Jaison', 'Uma'],
                   name='EmployeeHike')
print(hikes)

Mani      10.5
Rahul      6.5
Jaison     7.5
Uma        5.5
Name: EmployeeHike, dtype: float64

In [ ]:
# Boolean Masking 
hikes > 6

Mani       True
Rahul      True
Jaison     True
Uma       False
Name: EmployeeHike, dtype: bool

In [ ]:
hikes[hikes > 6]

# float64 - more decimal digit values

Mani      10.5
Rahul      6.5
Jaison     7.5
Name: EmployeeHike, dtype: float64

In [13]:
# Pandas DataFrame is a two-dimensional labeled data structure with columns of potentially different types. 
# It is similar to a spreadsheet or SQL table, and it is one of the most commonly used data structures in the pandas library. 
# A DataFrame can be thought of as a collection of Series objects that share the same index.
# A DataFrame can be created from various data sources, such as dictionaries, lists, or

data = {
    'Name' : ['Usha', 'Parthiban', 'Shankar', 'Alice'],
    'Age' : [24,35,26,40],
    'Experience': [2,4,5,6]
}

print(data)

{'Name': ['Usha', 'Parthiban', 'Shankar', 'Alice'], 'Age': [24, 35, 26, 40], 'Experience': [2, 4, 5, 6]}

In [14]:
df = pd.DataFrame(data)
print(df)

        Name  Age  Experience
0       Usha   24           2
1  Parthiban   35           4
2    Shankar   26           5
3      Alice   40           6

In [15]:
df.head()

        Name  Age  Experience
0       Usha   24           2
1  Parthiban   35           4
2    Shankar   26           5
3      Alice   40           6

In [16]:
df.head(2)

        Name  Age  Experience
0       Usha   24           2
1  Parthiban   35           4

In [19]:
df.tail(2)

      Name  Age  Experience
2  Shankar   26           5
3    Alice   40           6

In [20]:
df.shape

(4, 3)

In [21]:
df.dtypes

Name            str
Age           int64
Experience    int64
dtype: object

In [22]:
df.describe()

             Age  Experience
count   4.000000    4.000000
mean   31.250000    4.250000
std     7.544314    1.707825
min    24.000000    2.000000
25%    25.500000    3.500000
50%    30.500000    4.500000
75%    36.250000    5.250000
max    40.000000    6.000000

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Age         4 non-null      int64
 2   Experience  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [24]:
import numpy as np

In [34]:
n = 50
df = pd.DataFrame({
    'emp_id' : range(1001, 1001+n),
    'name' : [f'Employee_{i}' for i in range(n)],
    'age' : np.random.randint(25, 40, n),
    'dept' : np.random.choice(['Engineering', 'HR', 'Sales'], n),
    'rating': np.random.choice([1,2,3,4,5], n)
})
df

    emp_id         name  age         dept  rating
0     1001   Employee_0   33           HR       1
1     1002   Employee_1   35           HR       1
2     1003   Employee_2   29  Engineering       1
3     1004   Employee_3   29        Sales       3
4     1005   Employee_4   26  Engineering       2
5     1006   Employee_5   26  Engineering       2
6     1007   Employee_6   35  Engineering       5
7     1008   Employee_7   27        Sales       3
8     1009   Employee_8   35        Sales       1
9     1010   Employee_9   27           HR       5
10    1011  Employee_10   32  Engineering       1
11    1012  Employee_11   32        Sales       5
12    1013  Employee_12   27  Engineering       2
13    1014  Employee_13   26  Engineering       4
14    1015  Employee_14   35  Engineering       2
15    1016  Employee_15   35  Engineering       5
16    1017  Employee_16   37  Engineering       1
17    1018  Employee_17   36  Engineering       3
18    1019  Employee_18   35           HR       2
19    1020  Employee_19   35           HR       2
20    1021  Employee_20   35           HR       3
21    1022  Employee_21   34  Engineering       3
22    1023  Employee_22   34  Engineering       5
23    1024  Employee_23   35        Sales       4
24    1025  Employee_24   33           HR       2
25    1026  Employee_25   29        Sales       5
26    1027  Employee_26   34        Sales       2
27    1028  Employee_27   34        Sales       2
28    1029  Employee_28   28        Sales       5
29    1030  Employee_29   37        Sales       1
30    1031  Employee_30   30  Engineering       2
31    1032  Employee_31   28           HR       4
32    1033  Employee_32   37           HR       3
33    1034  Employee_33   25        Sales       2
34    1035  Employee_34   38           HR       2
35    1036  Employee_35   36           HR       5
36    1037  Employee_36   33        Sales       2
37    1038  Employee_37   33  Engineering       1
38    1039  Employee_38   33           HR       3
39    1040  Employee_39   28           HR       3
40    1041  Employee_40   33           HR       1
41    1042  Employee_41   26        Sales       1
42    1043  Employee_42   27           HR       2
43    1044  Employee_43   26  Engineering       2
44    1045  Employee_44   27  Engineering       5
45    1046  Employee_45   36        Sales       5
46    1047  Employee_46   27           HR       4
47    1048  Employee_47   39        Sales       2
48    1049  Employee_48   28           HR       3
49    1050  Employee_49   34           HR       2

In [33]:
df.head()

   emp_id        name  age         dept  rating
0    1001  Employee_0   27        Sales       2
1    1002  Employee_1   32  Engineering       1
2    1003  Employee_2   25           HR       2
3    1004  Employee_3   33           HR       3
4    1005  Employee_4   36        Sales       2

In [ ]:
# Randing choosing the value, Everytime you run the code, the new value will pop up 
np.random.randint(25, 40, n),

(array([27, 35, 25, 30, 28, 37, 36, 34, 31, 39, 31, 38, 39, 33, 32, 25, 30,
        31, 36, 31, 38, 29, 39, 25, 28, 37, 39, 25, 35, 25, 31, 29, 39, 30,
        37, 28, 33, 38, 38, 28, 34, 39, 39, 35, 38, 33, 39, 31, 39, 25],
       dtype=int32),)

In [35]:
# Want to take only the rating column 
df['rating'].head()

0    1
1    1
2    1
3    3
4    2
Name: rating, dtype: int64

In [39]:
# Want to have two column -> need rating and name column 
df[['name' ,'rating']].head()

         name  rating
0  Employee_0       1
1  Employee_1       1
2  Employee_2       1
3  Employee_3       3
4  Employee_4       2

In [41]:
# Need 3 rows and column 

df.loc[1:3 , ['name', 'rating']]

         name  rating
1  Employee_1       1
2  Employee_2       1
3  Employee_3       3

In [42]:
df.iloc[0]

emp_id          1001
name      Employee_0
age               33
dept              HR
rating             1
Name: 0, dtype: object

In [43]:
# Need to change to DICTINARY

df.iloc[0].to_dict()

{'emp_id': 1001, 'name': 'Employee_0', 'age': 33, 'dept': 'HR', 'rating': 1}

In [66]:
# Last 2 rows and First 2 Columns - Revise Index
df.iloc[-2:, :3]

    emp_id         name  age
48    1049  Employee_48   28
49    1050  Employee_49   34

In [48]:
df['rating']>2

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7      True
8     False
9      True
10    False
11     True
12    False
13     True
14    False
15     True
16    False
17     True
18    False
19    False
20     True
21     True
22     True
23     True
24    False
25     True
26    False
27    False
28     True
29    False
30    False
31     True
32     True
33    False
34    False
35     True
36    False
37    False
38     True
39     True
40    False
41    False
42    False
43    False
44     True
45     True
46     True
47    False
48     True
49    False
Name: rating, dtype: bool

In [54]:
# Filering 
df[df['rating'] > 2 ]

    emp_id         name  age         dept  rating  exp_years
3     1004   Employee_3   29        Sales       3          7
6     1007   Employee_6   35  Engineering       5          1
7     1008   Employee_7   27        Sales       3          4
9     1010   Employee_9   27           HR       5          6
11    1012  Employee_11   32        Sales       5          2
13    1014  Employee_13   26  Engineering       4          7
15    1016  Employee_15   35  Engineering       5          6
17    1018  Employee_17   36  Engineering       3          7
20    1021  Employee_20   35           HR       3          3
21    1022  Employee_21   34  Engineering       3          8
22    1023  Employee_22   34  Engineering       5          3
23    1024  Employee_23   35        Sales       4          8
25    1026  Employee_25   29        Sales       5          5
28    1029  Employee_28   28        Sales       5          3
31    1032  Employee_31   28           HR       4          8
32    1033  Employee_32   37           HR       3          9
35    1036  Employee_35   36           HR       5          3
38    1039  Employee_38   33           HR       3          2
39    1040  Employee_39   28           HR       3          3
44    1045  Employee_44   27  Engineering       5          2
45    1046  Employee_45   36        Sales       5          9
46    1047  Employee_46   27           HR       4          7
48    1049  Employee_48   28           HR       3          5

In [53]:
df[df['age'] > 35]

    emp_id         name  age         dept  rating  exp_years
16    1017  Employee_16   37  Engineering       1          7
17    1018  Employee_17   36  Engineering       3          7
29    1030  Employee_29   37        Sales       1          5
32    1033  Employee_32   37           HR       3          9
34    1035  Employee_34   38           HR       2          2
35    1036  Employee_35   36           HR       5          3
45    1046  Employee_45   36        Sales       5          9
47    1048  Employee_47   39        Sales       2          9

In [ ]:
#Betwwen Function
# Since it is number value - Using betwwen function 
df[df['rating'].between(1,3)]

    emp_id         name  age         dept  rating  exp_years
0     1001   Employee_0   33           HR       1          8
1     1002   Employee_1   35           HR       1          9
2     1003   Employee_2   29  Engineering       1          9
3     1004   Employee_3   29        Sales       3          7
4     1005   Employee_4   26  Engineering       2          1
5     1006   Employee_5   26  Engineering       2          8
7     1008   Employee_7   27        Sales       3          4
8     1009   Employee_8   35        Sales       1          4
10    1011  Employee_10   32  Engineering       1          3
12    1013  Employee_12   27  Engineering       2          2
14    1015  Employee_14   35  Engineering       2          5
16    1017  Employee_16   37  Engineering       1          7
17    1018  Employee_17   36  Engineering       3          7
18    1019  Employee_18   35           HR       2          8
19    1020  Employee_19   35           HR       2          2
20    1021  Employee_20   35           HR       3          3
21    1022  Employee_21   34  Engineering       3          8
24    1025  Employee_24   33           HR       2          5
26    1027  Employee_26   34        Sales       2          3
27    1028  Employee_27   34        Sales       2          6
29    1030  Employee_29   37        Sales       1          5
30    1031  Employee_30   30  Engineering       2          9
32    1033  Employee_32   37           HR       3          9
33    1034  Employee_33   25        Sales       2          7
34    1035  Employee_34   38           HR       2          2
36    1037  Employee_36   33        Sales       2          2
37    1038  Employee_37   33  Engineering       1          8
38    1039  Employee_38   33           HR       3          2
39    1040  Employee_39   28           HR       3          3
40    1041  Employee_40   33           HR       1          7
41    1042  Employee_41   26        Sales       1          3
42    1043  Employee_42   27           HR       2          3
43    1044  Employee_43   26  Engineering       2          7
47    1048  Employee_47   39        Sales       2          9
48    1049  Employee_48   28           HR       3          5
49    1050  Employee_49   34           HR       2          4

In [57]:
# if we have string value 

df[df['dept'].isin(['HR'])]

    emp_id         name  age dept  rating  exp_years
0     1001   Employee_0   33   HR       1          8
1     1002   Employee_1   35   HR       1          9
9     1010   Employee_9   27   HR       5          6
18    1019  Employee_18   35   HR       2          8
19    1020  Employee_19   35   HR       2          2
20    1021  Employee_20   35   HR       3          3
24    1025  Employee_24   33   HR       2          5
31    1032  Employee_31   28   HR       4          8
32    1033  Employee_32   37   HR       3          9
34    1035  Employee_34   38   HR       2          2
35    1036  Employee_35   36   HR       5          3
38    1039  Employee_38   33   HR       3          2
39    1040  Employee_39   28   HR       3          3
40    1041  Employee_40   33   HR       1          7
42    1043  Employee_42   27   HR       2          3
46    1047  Employee_46   27   HR       4          7
48    1049  Employee_48   28   HR       3          5
49    1050  Employee_49   34   HR       2          4

In [62]:
df[df['dept'].isin(['HR']) & (df['age'] > 25)]

    emp_id         name  age dept  rating  exp_years
0     1001   Employee_0   33   HR       1          8
1     1002   Employee_1   35   HR       1          9
9     1010   Employee_9   27   HR       5          6
18    1019  Employee_18   35   HR       2          8
19    1020  Employee_19   35   HR       2          2
20    1021  Employee_20   35   HR       3          3
24    1025  Employee_24   33   HR       2          5
31    1032  Employee_31   28   HR       4          8
32    1033  Employee_32   37   HR       3          9
34    1035  Employee_34   38   HR       2          2
35    1036  Employee_35   36   HR       5          3
38    1039  Employee_38   33   HR       3          2
39    1040  Employee_39   28   HR       3          3
40    1041  Employee_40   33   HR       1          7
42    1043  Employee_42   27   HR       2          3
46    1047  Employee_46   27   HR       4          7
48    1049  Employee_48   28   HR       3          5
49    1050  Employee_49   34   HR       2          4

In [46]:
exp = {
    'exp_years': np.random.randint(1,10,n)
}
print(exp)


df = df.assign(exp_years=exp['exp_years'])

{'exp_years': array([8, 9, 9, 7, 1, 8, 1, 4, 4, 6, 3, 2, 2, 7, 5, 6, 7, 7, 8, 2, 3, 8,
       3, 8, 5, 5, 3, 6, 3, 5, 9, 8, 9, 7, 2, 3, 2, 8, 2, 3, 7, 3, 3, 7,
       2, 9, 7, 9, 5, 4], dtype=int32)}